/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import naivebayesforeverything.DataSets;
import naivebayesforeverything.GetFromFile;
import naivebayesforeverything.ParseFromCSV;

/**
 *
 * @author adityaabu
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    DataSets D=null;
    JFileChooser fileChooser=null;
    JFileChooser fileChooserSNB=null;
    private  String path;
    public main() {
        initComponents();
        fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("CSV", "csv"));
        fileChooserSNB = new JFileChooser();
        fileChooserSNB.setFileFilter(new FileNameExtensionFilter("SNB", "snb"));
        butTestDataSets.setEnabled(false);
        butViewDataSets.setEnabled(false);
        butViewTestHistory.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        butViewDataSets = new javax.swing.JButton();
        butViewTestHistory = new javax.swing.JButton();
        butTestDataSets = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_File = new javax.swing.JMenu();
        Menu_New = new javax.swing.JMenuItem();
        Menu_OpenCSV = new javax.swing.JMenuItem();
        Menu_OpenSaveDataset = new javax.swing.JMenuItem();
        Menu_InsertManual = new javax.swing.JMenuItem();
        menuSaveSNB = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        butViewDataSets.setText("View Data Sets");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butViewTestHistory.setText("View Test History");
        butViewTestHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butViewTestHistoryActionPerformed(evt);
            }
        });

        butTestDataSets.setText("Test Data Sets");
        butTestDataSets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTestDataSetsActionPerformed(evt);
            }
        });

        Menu_File.setText("File");
        Menu_File.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                Menu_FileMenuSelected(evt);
            }
        });

        Menu_New.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Menu_New.setText("New");
        Menu_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_NewActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_New);

        Menu_OpenCSV.setText("Open CSV file");
        Menu_OpenCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_OpenCSVActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_OpenCSV);

        Menu_OpenSaveDataset.setText("Open from Saved Data Set");
        Menu_OpenSaveDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_OpenSaveDatasetActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_OpenSaveDataset);

        Menu_InsertManual.setText("Insert Manual");
        Menu_InsertManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_InsertManualActionPerformed(evt);
            }
        });
        Menu_File.add(Menu_InsertManual);

        menuSaveSNB.setText("Save into SNB file..");
        menuSaveSNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveSNBActionPerformed(evt);
            }
        });
        Menu_File.add(menuSaveSNB);
        Menu_File.add(jSeparator1);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Menu_File.add(Exit);

        jMenuBar1.add(Menu_File);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butTestDataSets, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(butViewTestHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(59, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butTestDataSets, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butViewTestHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_FileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_Menu_FileMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_FileMenuSelected

    private void Menu_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_NewActionPerformed
        D=null;
        butTestDataSets.setEnabled(false);
        butViewDataSets.setEnabled(false);
        butViewTestHistory.setEnabled(true);
    }//GEN-LAST:event_Menu_NewActionPerformed

    private void Menu_OpenSaveDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_OpenSaveDatasetActionPerformed
        int val = fileChooserSNB.showOpenDialog(this);
        if (val== JFileChooser.APPROVE_OPTION){
            path=fileChooserSNB.getSelectedFile().getPath();
            D = GetFromFile.getFrom(path);
            butTestDataSets.setEnabled(true);
            butViewDataSets.setEnabled(true);
            butViewTestHistory.setEnabled(true);
        }
    }//GEN-LAST:event_Menu_OpenSaveDatasetActionPerformed

    private void butViewTestHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butViewTestHistoryActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHistory().setVisible(true);
            }
        });
    }//GEN-LAST:event_butViewTestHistoryActionPerformed

    private void butTestDataSetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTestDataSetsActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDataTraining(D,path).setVisible(true);
                butTestDataSets.setVisible(true);
            }
        });
    }//GEN-LAST:event_butTestDataSetsActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_ExitActionPerformed

    private void Menu_OpenCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_OpenCSVActionPerformed
        int val = fileChooser.showOpenDialog(this);
        if (val== JFileChooser.APPROVE_OPTION){
            path=fileChooser.getSelectedFile().getPath();
            D = ParseFromCSV.ParseFromCSV(path);
            if (D!=null) {
                
                butTestDataSets.setEnabled(true);
                butViewDataSets.setEnabled(true);
                butViewTestHistory.setEnabled(true);
            }
        }
    }//GEN-LAST:event_Menu_OpenCSVActionPerformed

    private void menuSaveSNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveSNBActionPerformed
        if (D==null){
            JOptionPane.showMessageDialog(this, "Data Set masih Kosong!");
            return;
        }
        int val = fileChooserSNB.showSaveDialog(this);
        if (val==JFileChooser.APPROVE_OPTION){
            try {
                String path=fileChooserSNB.getSelectedFile().getAbsolutePath();
                if (!path.contains(".snb")) path+=".snb" ;
                ObjectOutputStream ob = new ObjectOutputStream(new FileOutputStream(path));
                ob.writeObject(D);
                ob.flush();
                ob.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
    }//GEN-LAST:event_menuSaveSNBActionPerformed

    private void Menu_InsertManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_InsertManualActionPerformed
        D= new DataSets();
        path="Manual insertion";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertManual(D).setVisible(true);
                butTestDataSets.setEnabled(true);
            }
        });
    }//GEN-LAST:event_Menu_InsertManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu Menu_File;
    private javax.swing.JMenuItem Menu_InsertManual;
    private javax.swing.JMenuItem Menu_New;
    private javax.swing.JMenuItem Menu_OpenCSV;
    private javax.swing.JMenuItem Menu_OpenSaveDataset;
    private javax.swing.JButton butTestDataSets;
    private javax.swing.JButton butViewDataSets;
    private javax.swing.JButton butViewTestHistory;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuSaveSNB;
    // End of variables declaration//GEN-END:variables
}
