/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import naivebayesforeverything.DataSets;
import naivebayesforeverything.Element;
import naivebayesforeverything.Groups;
import naivebayesforeverything.History;
import naivebayesforeverything.MainSet;

/**
 *
 * @author adityaabu
 */
public class TestDataTraining extends javax.swing.JFrame {

    
    private DataSets D;
    private int i=0;
    ArrayList<String> s;
    private String path;
    public TestDataTraining() {
        initComponents();
    }

     public TestDataTraining(DataSets d,String path) {
        initComponents();
        this.D=d;
        s=new ArrayList();
        this.path=path;
        updateBox();
        
        
    }
     private void updateBox(){
         labelColumn.setText(D.getColumnAt(i)+" :");
         comboElement.removeAllItems();
         ArrayList<String> l= new ArrayList();
         for (Object o: D.getMainSets()){
             MainSet m = (MainSet)o;
             Groups G =m.getGroupAt(i);
             for (Object E: G.getElements()){
                 if (!l.contains(((Element)E).getName())) l.add(((Element)E).getName());
             }
         }
         for (String s_: l){
             comboElement.addItem(s_);
         }
         l.clear();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboElement = new javax.swing.JComboBox();
        butNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        labelColumn = new javax.swing.JLabel();
        butCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butNext.setText("Next");
        butNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNextActionPerformed(evt);
            }
        });

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        labelColumn.setText("jLabel1");

        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboElement, 0, 252, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(butNext, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butCancel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelColumn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboElement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butNext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butCancel)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNextActionPerformed

        if (i<D.getColumnSize()-2){

            s.add((String)comboElement.getModel().getSelectedItem());
            txt.setText(txt.getText()+"\n"+labelColumn.getText()+comboElement.getModel().getSelectedItem());
            i++;
            updateBox();
        }
        else if (butNext.getText().equals("Finish")){
            
            String result="";
            double max=0.0,cur=1.0;
            int i;
            for (Object O: D.getMainSets()){
                i=0;
                cur=1.0;
                MainSet M = (MainSet) O;
                for (Object G : M.getGroups()){
                    Groups g= (Groups) G;
                    for (Object E: g.getElements()){
                        Element e = (Element) E;
                        if(e.getName().equals(s.get(i))) cur*=((double)e.getJumlah()/D.getTotal(e.getName(), g.getName()));
                    }
                    i++;
                }
                cur*=(double)M.getTotal()/D.getTotalMain();
                
                if (cur>max){
                    max=cur;
                    result=M.getName();
                }
                
            }
            int val =JOptionPane.showConfirmDialog(this, "Hasilnya: "+result+"\nApakah anda ingin menyimpannya? Tekan Yes jika jawabannya benar"
                + "\nTekan No jika Jawabannya Salah\nTekan Cancel jika anda tidak ingin menyimpannya");
            if (val==JOptionPane.OK_OPTION || val == JOptionPane.NO_OPTION) {
                Date d = new Date();
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                History h = new History();
                h.read();
                h.addHistory(new String[] {dateFormat.format(d), path, (val==JOptionPane.OK_OPTION)+""});
                h.write();
            }
            dispose();
        }
        else {
            butNext.setText("Finish");
            s.add((String)comboElement.getModel().getSelectedItem());
            txt.setText(txt.getText()+"\n"+labelColumn.getText()+comboElement.getModel().getSelectedItem());
            i++;
            updateBox();
        }
        
    }//GEN-LAST:event_butNextActionPerformed

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        dispose();
    }//GEN-LAST:event_butCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancel;
    private javax.swing.JButton butNext;
    private javax.swing.JComboBox comboElement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelColumn;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
